version: '3.9'

services:
  java-app:
    container_name: java-app
    image: sespitia-weather-app-docker:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://weather-app-db:3306/weather_station?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=admin
    depends_on:
      - weather-app-db
  weather-app-db:
    container_name: weather-app-db
    image: mysql:8.0
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: weather_station
      MYSQL_USER: santi
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin